### ISSUE TITLE
all header(h1,h2,...etc) elements with one alignment

### ISSUE THREAD

**Issue by qhhonx** [ifraixedes/browser-extension-github-readme-toc#1]
###### Could you please make it more human readable like the following left part displaying way?

![qq 20150705184414](https://cloud.githubusercontent.com/assets/2561942/8511388/2c893f88-2346-11e5-9765-071d20f6e9b5.png)

**Comment by ifraixedes** [comment]
OK, I'll try to find time to make that change.

Thanks for reporting it.

**Comment by ifraixedes** [comment]
Hi @xohozu 

I've got some time to fixed, however I don't think that your proposal is very appropriated because the bullets take space in the screen and for screens which aren't larger the white space in the right side isn't very wide.

My solution, which is under PR #2 is use indentation (padding left) fro each Header level.

The same example that you posted looks as

<img width="278" alt="screen shot 2015-07-05 at 19 29 47" src="https://cloud.githubusercontent.com/assets/1731633/8512828/ff5057d4-234c-11e5-86be-c8e42fba86c1.png">

What do you think?

**Comment by qhhonx** [comment]
awesome, you got my idea, it just needs indentation to display hierarchy.
 I love this TOC extension because it puts the TOC content in the right of content-box not top.
What do you think if the TOC content can be fixed when I scroll down?

**Comment by ifraixedes** [comment]
> What do you think if the TOC content can be fixed when I scroll down?

You mean to be always able to see it?

**Comment by qhhonx** [comment]
right, it can help us to locate every part easily, do you agree?

**Comment by ifraixedes** [comment]
OK, I think that it's a good idea; I've created issue #3 to release in a future release, hopefully I'll find time next weekend.

Regarding to this I think that I should release this version which is under PR #2 and close this issue when I update the release in Chrome Web Store

**Comment by ifraixedes** [comment]
Updated chrome extension in webstore
